/**
 * TolimaGO - Datos de Ubicaciones
 * Municipios del Tolima, países y ciudades para el sistema de registro
 */

// Municipios del Tolima (47 municipios)
export const tolimaMunicipalities = [
  "Ibagué", // Capital
  "Espinal",
  "Girardot",
  "Melgar",
  "Honda",
  "Líbano",
  "Chaparral",
  "Purificación",
  "Flandes",
  "Mariquita",
  "Guamo",
  "Saldaña",
  "Armero-Guayabal",
  "Venadillo",
  "Piedras",
  "Coello",
  "Rovira",
  "San Luis",
  "Fresno",
  "Herveo",
  "Lérida",
  "Ambalema",
  "Cajamarca",
  "Anzoátegui",
  "Santa Isabel",
  "Falan",
  "Palocabildo",
  "Casabianca",
  "Roncesvalles",
  "Ortega",
  "Dolores",
  "Alpujarra",
  "Prado",
  "Cunday",
  "Villarrica",
  "Planadas",
  "Ataco",
  "Rioblanco",
  "Coyaima",
  "Natagaima",
  "Suárez",
  "Carmen de Apicalá",
  "Icononzo",
  "Murillo",
  "Villahermosa",
  "Alvarado",
  "Valle de San Juan",
].sort();

// Países más comunes
export const countries = [
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "CA", name: "Canadá", flag: "🇨🇦" },
  { code: "MX", name: "México", flag: "🇲🇽" },
  { code: "ES", name: "España", flag: "🇪🇸" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "BR", name: "Brasil", flag: "🇧🇷" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "PE", name: "Perú", flag: "🇵🇪" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", name: "Panamá", flag: "🇵🇦" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "DO", name: "República Dominicana", flag: "🇩🇴" },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "FR", name: "Francia", flag: "🇫🇷" },
  { code: "DE", name: "Alemania", flag: "🇩🇪" },
  { code: "IT", name: "Italia", flag: "🇮🇹" },
  { code: "GB", name: "Reino Unido", flag: "🇬🇧" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "JP", name: "Japón", flag: "🇯🇵" },
  { code: "KR", name: "Corea del Sur", flag: "🇰🇷" },
  { code: "CN", name: "China", flag: "🇨🇳" },
].sort((a, b) => a.name.localeCompare(b.name));

// Departamentos/Estados de Colombia
export const colombianDepartments = [
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "San Andrés y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
  "Bogotá D.C.",
].sort();

// Principales ciudades por país (ejemplo para algunos países)
export const citiesByCountry: Record<string, string[]> = {
  CO: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Soledad",
    "Ibagué",
    "Bucaramanga",
    "Soacha",
    "Pereira",
    "Santa Marta",
    "Villavicencio",
    "Valledupar",
    "Manizales",
    "Montería",
    "Pasto",
    "Neiva",
    "Armenia",
    "Sincelejo",
  ].sort(),

  US: [
    "Nueva York",
    "Los Ángeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San José",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington D.C.",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Mesa",
    "Sacramento",
    "Atlanta",
    "Kansas City",
    "Colorado Springs",
    "Miami",
    "Raleigh",
    "Omaha",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
  ].sort(),

  MX: [
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Torreón",
    "Querétaro",
    "San Luis Potosí",
    "Mérida",
    "Mexicali",
    "Aguascalientes",
    "Cuernavaca",
    "Saltillo",
    "Hermosillo",
    "Culiacán",
    "Chihuahua",
    "Morelia",
    "Tampico",
  ].sort(),

  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Hospitalet",
    "A Coruña",
    "Vitoria",
    "Granada",
    "Elche",
  ].sort(),

  AR: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "San Miguel de Tucumán",
    "La Plata",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Neuquén",
    "Santiago del Estero",
    "Corrientes",
    "Posadas",
    "Bahía Blanca",
    "Paraná",
    "Formosa",
    "San Luis",
    "La Rioja",
  ].sort(),
};

export type LocationData = {
  country?: string;
  state?: string;
  city?: string;
  isTolima: boolean;
};
